-- MySQL Script generated by MySQL Workbench
-- Thu Dec  9 21:59:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema football_club
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema football_club
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `football_club` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `football_club` ;

-- -----------------------------------------------------
-- Table `football_club`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_club`.`club` (
  `name` VARCHAR(45) NOT NULL,
  `number_of_trophy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `football_club`.`affiliate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_club`.`affiliate` (
  `affiliate_number` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `addres` VARCHAR(45) NOT NULL,
  `antiquity` VARCHAR(45) NULL DEFAULT NULL,
  `club` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`affiliate_number`, `club`),
  INDEX `affilate_idx` (`club` ASC) VISIBLE,
  CONSTRAINT `affilate`
    FOREIGN KEY (`club`)
    REFERENCES `football_club`.`club` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `football_club`.`leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_club`.`leagues` (
  `team_name` VARCHAR(45) NOT NULL,
  `league` ENUM('PRIMERA', 'SEGUNDA', 'TERCERA') NULL DEFAULT NULL,
  PRIMARY KEY (`team_name`),
  UNIQUE INDEX `team_name_UNIQUE` (`team_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `football_club`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football_club`.`player` (
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL, //se cambia el charset
  `goals` INT NULL DEFAULT NULL,
  `position` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `team` VARCHAR(45) NULL DEFAULT NULL,#cant foreign key name in club
  PRIMARY KEY (`name`),     
  INDEX `name_idx` (`team` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
